export const STYLE_DATA = {
  a: [
    'alignContent', 
    'alignItems', 
    'alignSelf', 
    'all', 
    'animation', 
    'animationDelay', 
    'animationDirection', 
    'animationDuration', 
    'animationFillMode',
    'animationIterationCount',
    'animationName',
    'animationPlayState',
    'animationTimingFunction',
  ],
  b: [
    'backfaceVisibility',
    'background',
    'backgroundAttachment',
    'backgroundBlendMode',
    'backgroundClip',
    'backgroundColor',
    'backgroundImage',
    'backgroundOrigin',
    'backgroundPosition',
    'backgroundRepeat',
    'backgroundSize',
    'border',
    'borderBottom',
    'borderBottomColor',
    'borderBottomLeftRadius',
    'borderBottomRightRadius',
    'borderBottomStyle',
    'borderBottomWidth',
    'borderCollapse',
    'borderColor',
    'borderImage',
    'borderImageOutset',
    'borderImageRepeat',
    'borderImageSlice',
    'borderImageSource',
    'borderImageWidth',
    'borderLeft',
    'borderLeftColor',
    'borderLeftStyle',
    'borderLeftWidth',
    'borderRadius',
    'borderRight',
    'borderRightColor',
    'borderRightStyle',
    'borderRightWidth',
    'borderSpacing',
    'borderStyle',
    'borderTop',
    'borderTopColor',
    'borderTopLeftRadius',
    'borderTopRightRadius',
    'borderTopStyle',
    'borderTopWidth',
    'borderWidth',
    'bottom',
    'boxDecorationBreak',
    'boxShadow',
    'boxSizing',
    'breakAfter',
    'breakBefore',
    'breakInside',
  ],
  c: [
    'captionSide',
    'caretColor',
    'clear',
    'clip',
    'clipPath',
    'color',
    'columnCount',
    'columnFill',
    'columnGap',
    'columnRule',
    'columnRuleColor',
    'columnRuleStyle',
    'columnRuleWidth',
    'columnSpan',
    'columnWidth',
    'columns',
    'content',
    'counterIncrement',
    'counterReset',
    'cursor',
  ],
  d: [
    'direction',
    'display',
  ],
  e: [
    'emptyCells',
  ],
  f: [
    'filter',
    'flex',
    'flexBasis',
    'flexDirection',
    'flexFlow',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'float',
    'font',
    '@fontFace',
    'fontFamily',
    'fontFeatureSettings',
    'fontKerning',
    'fontSize',
    'fontSizeAdjust',
    'fontStretch',
    'fontStyle',
    'fontSynthesis',
    'fontVariant',
    'fontVariantAlternates',
    'fontVariantCaps',
    'fontVariantEastAsian',
    'fontVariantLigatures',
    'fontVariantNumeric',
    'fontVariantPosition',
    'fontWeight',
  ],
  g: [
    'grid',
    'gridArea',
    'gridAutoColumns',
    'gridAutoFlow',
    'gridAutoRows',
    'gridColumn',
    'gridColumnEnd',
    'gridColumnGap',
    'gridColumnStart',
    'gridGap',
    'gridRow',
    'gridRowEnd',
    'gridRowGap',
    'gridRowStart',
    'gridTemplate',
    'gridTemplateAreas',
    'gridTemplateColumns',
    'gridTemplateRows',
  ],
  h: [
    'hangingPunctuation',
    'height',
    'hyphens',
  ],
  j: [
    'justifyContent',
  ],
  l: [
    'left',
    'letterSpacing',
    'lineBreak',
    'lineHeight',
    'listStyle',
    'listStyleImage',
    'listStylePosition',
    'listStyleType',
  ],
  m: [
    'margin',
    'marginBottom',
    'marginLeft',
    'marginRight',
    'marginTop',
    'mask',
    'maskType',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'mixBlendMode',
  ],
  o: [
    'objectFit',
    'objectPosition',
    'opacity',
    'order',
    'outline',
    'outlineColor',
    'outlineOffset',
    'outlineStyle',
    'outlineWidth',
    'overflow',
    'overflowX',
    'overflowY',
  ],
  p: [
    'padding',
    'paddingBottom',
    'paddingLeft',
    'paddingRight',
    'paddingTop',
    'pageBreakAfter',
    'pageBreakBefore',
    'pageBreakInside',
    'perspective',
    'perspectiveOrigin',
    'pointerEvents',
    'position',
  ],
  q: [
    'quotes',
  ],
  r: [
    'resize',
    'right',
  ],
  s: [
    'scrollBehavior',
  ],
  t: [
    'tabSize',
    'tableLayout',
    'textAlign',
    'textAlignLast',
    'textDecoration',
    'textDecorationColor',
    'textDecorationLine',
    'textDecorationStyle',
    'textIndent',
    'textJustify',
    'textOverflow',
    'textShadow',
    'textTransform',
    'top',
    'transform',
    'transformOrigin',
    'transformStyle',
    'transition',
    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
  ],
  u: [
    'unicodeBidi',
    'userSelect',
  ],
  v: [
    'verticalAlign',
    'visibility',
  ],
  w: [
    'whiteSpace',
    'width',
    'wordBreak',
    'wordSpacing',
    'wordWrap',
    'writingMode',
  ],
  z: [
    'zIndex',
  ]
} as any;



export const STYLE_ALL_DATA = {
  alignContent: ['stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around', 'initial', 'inherit'],
  alignItems: ['stretch', 'center', 'flex-start', 'flex-end', 'baseline', 'initial', 'inherit'],
  alignSelf: ['auto','stretch','center','flex-start','flex-end','baseline','initial','inherit'],
  backgroundOrigin: ['padding-box','border-box','content-box'],
  backgroundRepeat: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat', 'inherit'],
  boxSizing: ['content-box','border-box','inherit'],
  clear: ['left', 'right', 'both', 'none', 'inherit'],
  columnFill: ['balance', 'auto'],
  columnRuleStyle: ['none','hidden','dotted','dashed','solid','double','groove','ridge','inset','outset'],
  direction: ['ltr', 'rtl', 'inherit'],
  display: [
    'none', 
    'block', 
    'flex',
    'inline', 
    'inline-block', 
    'list-item',
    'run-in',
    'compact',
    'marker',
    'table',
    'inline-table',
    'table-row-group',
    'table-header-group',
    'table-footer-group',
    'table-row',
    'table-column-group',
    'table-column',
    'table-cell',
    'table-caption',
    'inherit',
  ],
  flexDirection: ['row', 'column', 'row-reverse', 'column-reverse', 'unset', 'inherit', 'initial'],
  font: ['left', 'right', 'none', 'inherit'],
  justifyContent: ['flex-start','flex-end','center','space-between','space-around','initial','inherit'],
  position: ['absolute', 'fixed', 'relative', 'static', 'inherit'],
  whiteSpace: ['normal', 'pre', 'nowrap', 'pre-wrap', 'pre-line', 'inherit'],
  wordBreak: ['normal','break-all','keep-all'],
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'inherit'],
} as any;